# Generated by Django 6.1.1 on 2026-09-24 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=120, verbose_name='Nombre de Contacto')),
                ('empresa', models.CharField(max_length=120, verbose_name='Raz+on Social / Empresa')),
                ('rut_empresa', models.CharField(blank=True, max_length=15, null=True, verbose_name='RUT Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Notas adicionales')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Total Cotizado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('RESPONDIDA', 'Respondida'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Unitario Histórico')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='catalogo.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotizacion',
                'verbose_name_plural': 'Detalles de Cotizacion',
            },
        ),
    ]
