# Generated by Django 6.1.1 on 2026-10-02 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_cotizacion_detallecotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa',
            field=models.CharField(max_length=150, verbose_name='Razón Social / Empresa'),
        ),
    ]
