# Generated by Django 6.1.1 on 2026-10-06 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_cotizacion_usuario_alter_cotizacion_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_total',
            field=models.IntegerField(default=0, verbose_name='Descuentos Totales'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='dias_validez',
            field=models.IntegerField(default=15, verbose_name='Validez'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ejecutivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_gestionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.IntegerField(default=0, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pais',
            field=models.CharField(default='Chile', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_neto',
            field=models.IntegerField(default=0, verbose_name='Subtotal Neto'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='porcentaje_descuento',
            field=models.IntegerField(default=0, verbose_name='Descuento Aplicado'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Subtotal'),
        ),
    ]
